### ISSUE TITLE
Violation of PRIMARY KEY constraint 'PK__#filtere__78EB98E0C389FB3D'. Cannot insert duplicate key in object 'dbo.#filtered_index_columns_analysis'.

### ISSUE THREAD

**Issue by georgejo** [erikdarlingdata/DarlingData#558]
**Version of the script**
        @version = '1.4.4',
        @version_date = '20250404';

**What is the current behavior?**

Msg 2627, Level 14, State 1, Procedure sp_IndexCleanup, Line 2486 [Batch Start Line 0]
Violation of PRIMARY KEY constraint 'PK__#filtere__78EB98E0C389FB3D'. Cannot insert duplicate key in object 'dbo.#filtered_index_columns_analysis'. The duplicate key value is (11, 1, 1226487448, 10).

**If the current behavior is a bug, please provide the steps to reproduce.**

sp_IndexCleanup @get_all_databases=1

**What is the expected behavior?**

Erik's super output

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures

Microsoft SQL Server 2016 (SP2-CU15) (KB4577775) - 13.0.5850.14 (X64)   Sep 17 2020 22:12:45   
Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by erikdarlingdata** [comment]
@georgejo thanks for reporting this. I got a similar one several days ago (#551) and issued a minor patch to fix it -- can you re-pull the code and let me know if it's still happening?

**Comment by bwiggins10** [comment]
@erikdarlingdata  - I am running into the same issue on the latest release

sp_IndexCleanup @get_all_databases=1

Msg 2627, Level 14, State 1, Procedure sp_IndexCleanup, Line 2486 [Batch Start Line 1]
Violation of PRIMARY KEY constraint 'PK__#filtere__78EB98E0994E9FDF'. Cannot insert duplicate key in object 'dbo.#filtered_index_columns_analysis'. The duplicate key value is (10, 5, 1749581271, 2).

Microsoft SQL Server 2019 (RTM-CU30) (KB5049235) - 15.0.4415.2 (X64) Nov 18 2024 17:45:37 
Copyright (C) 2019 Microsoft Corporation Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by erikdarlingdata** [comment]
@bwiggins10 @georgejo i just pushed a change to the dev branch. can you let me know if you're still hitting the error? I don't have the same issue locally, and I don't understand the root cause based on what you're seeing, so I'm just taking a guess here.

**Comment by erikdarlingdata** [comment]
@bwiggins10 ah! that is helpful, thank you. I've pushed another change to change the clustered primary key on the table to a non-unique clustered index.

I don't have the weird character thing for ANSI_WARNINGS, though.

**Comment by bwiggins10** [comment]
@erikdarlingdata  Just tried the new version from the DEV branch - No more duplicate keys issue! 😄 
There's 1300 additional rows returned in the DEV version compared to MAIN (I imagine it's from other changes made to that branch that aren't in release yet, but incase it's not, I figured it was worth a mention).

On a side note, I do still see that it's inserting a bunch of duplicates into #filtered_index_columns_analysis:
![Image](https://github.com/user-attachments/assets/6c638e9e-24e7-44e9-83ad-00eca9366144)

As for the ANSI_WARNINGS:
Seems there's a hidden character in the dev branch:
![Image](https://github.com/user-attachments/assets/1c5f4ff4-9c49-4cb8-bfe3-64c710d0987b)

Github also showing a weird difference between them:
![Image](https://github.com/user-attachments/assets/762529f9-54f3-45b4-8ab2-49faffe391f2)

**Comment by erikdarlingdata** [comment]
@bwiggins10 I'm not sure what to do there. When I delete that line and replace it with a freshly typed one, then save the file, GitHub doesn't see any changes to push. I do believe there's something weird there, just not sure how to fix it quickly. 

I'm glad the other change got you past the error though.

**Comment by bwiggins10** [comment]
@erikdarlingdata I accidentally selected my own repo for my PR at first that resolves the duplicates, I've corrected it now - See #559

**Comment by erikdarlingdata** [comment]
@bwiggins10 no problem. I made an additional change to pull out the dupes. Perhaps the 👻 character is gone now too.
